/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.apis

import equisoft/openapi.models.MxrecipientsPayload
import equisoft/openapi.models.MxvalidateRecipientsResponse

import equisoft/openapi.infrastructure.ApiClient
import equisoft/openapi.infrastructure.ClientException
import equisoft/openapi.infrastructure.ClientError
import equisoft/openapi.infrastructure.ServerException
import equisoft/openapi.infrastructure.ServerError
import equisoft/openapi.infrastructure.MultiValueMap
import equisoft/openapi.infrastructure.RequestConfig
import equisoft/openapi.infrastructure.RequestMethod
import equisoft/openapi.infrastructure.ResponseType
import equisoft/openapi.infrastructure.Success
import equisoft/openapi.infrastructure.toMultiValue

class MxApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("equisoft/openapi.baseUrl", "http://localhost")
        }
    }

    /**
    * Validate recipients
    * 
    * @param mxrecipientsPayload  
    * @return MxvalidateRecipientsResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun validateRecipients(mxrecipientsPayload: MxrecipientsPayload) : MxvalidateRecipientsResponse {
        val localVariableConfig = validateRecipientsRequestConfig(mxrecipientsPayload = mxrecipientsPayload)

        val localVarResponse = request<MxvalidateRecipientsResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MxvalidateRecipientsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation validateRecipients
    *
    * @param mxrecipientsPayload  
    * @return RequestConfig
    */
    fun validateRecipientsRequestConfig(mxrecipientsPayload: MxrecipientsPayload) : RequestConfig {
        val localVariableBody: kotlin.Any? = mxrecipientsPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.POST,
            path = "/crm/api/app/mail/validateRecipients",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
