/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk

import com.equisoft.connect.sdk.models.RemoteaccountAccountSyncResponse

import com.equisoft.connect.sdk.infrastructure.ApiClient
import com.equisoft.connect.sdk.infrastructure.ClientException
import com.equisoft.connect.sdk.infrastructure.ClientError
import com.equisoft.connect.sdk.infrastructure.ServerException
import com.equisoft.connect.sdk.infrastructure.ServerError
import com.equisoft.connect.sdk.infrastructure.MultiValueMap
import com.equisoft.connect.sdk.infrastructure.RequestConfig
import com.equisoft.connect.sdk.infrastructure.RequestMethod
import com.equisoft.connect.sdk.infrastructure.ResponseType
import com.equisoft.connect.sdk.infrastructure.Success
import com.equisoft.connect.sdk.infrastructure.toMultiValue

class RemoteAccountApi(
    basePath: kotlin.String = defaultBasePath,
    accessToken: String? = null
) : ApiClient(basePath, accessToken) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("com.equisoft.connect.sdk.baseUrl", "http://localhost")
        }
    }

    /**
    * Synchronize calendars with remote account
    * 
    * @param dateTimeStart  (optional)
    * @param dateTimeEnd  (optional)
    * @param webuserCalendarIds  (optional)
    * @param remoteFolderIds  (optional)
    * @param webuserIds  (optional)
    * @return RemoteaccountAccountSyncResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun synchronizeCalendars(dateTimeStart: kotlin.String?, dateTimeEnd: kotlin.String?, webuserCalendarIds: kotlin.collections.List<kotlin.Int>?, remoteFolderIds: kotlin.collections.List<kotlin.Int>?, webuserIds: kotlin.collections.List<kotlin.Int>?) : RemoteaccountAccountSyncResponse {
        val localVariableConfig = synchronizeCalendarsRequestConfig(dateTimeStart = dateTimeStart, dateTimeEnd = dateTimeEnd, webuserCalendarIds = webuserCalendarIds, remoteFolderIds = remoteFolderIds, webuserIds = webuserIds)

        val localVarResponse = request<Map<String, Any?>, RemoteaccountAccountSyncResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemoteaccountAccountSyncResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation synchronizeCalendars
    *
    * @param dateTimeStart  (optional)
    * @param dateTimeEnd  (optional)
    * @param webuserCalendarIds  (optional)
    * @param remoteFolderIds  (optional)
    * @param webuserIds  (optional)
    * @return RequestConfig
    */
    fun synchronizeCalendarsRequestConfig(dateTimeStart: kotlin.String?, dateTimeEnd: kotlin.String?, webuserCalendarIds: kotlin.collections.List<kotlin.Int>?, remoteFolderIds: kotlin.collections.List<kotlin.Int>?, webuserIds: kotlin.collections.List<kotlin.Int>?) : RequestConfig<Map<String, Any?>> {
        val localVariableBody = mapOf("dateTimeStart" to dateTimeStart, "dateTimeEnd" to dateTimeEnd, "webuserCalendarIds" to webuserCalendarIds, "remoteFolderIds" to remoteFolderIds, "webuserIds" to webuserIds)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "application/x-www-form-urlencoded")

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/crm/api/agenda/account/calendarSync",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Synchronize tasks with remote account
    * 
    * @param dateTimeStart  (optional)
    * @param dateTimeEnd  (optional)
    * @param webuserCalendarIds  (optional)
    * @param remoteFolderIds  (optional)
    * @param webuserIds  (optional)
    * @return RemoteaccountAccountSyncResponse
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun synchronizeTasks(dateTimeStart: kotlin.String?, dateTimeEnd: kotlin.String?, webuserCalendarIds: kotlin.collections.List<kotlin.Int>?, remoteFolderIds: kotlin.collections.List<kotlin.Int>?, webuserIds: kotlin.collections.List<kotlin.Int>?) : RemoteaccountAccountSyncResponse {
        val localVariableConfig = synchronizeTasksRequestConfig(dateTimeStart = dateTimeStart, dateTimeEnd = dateTimeEnd, webuserCalendarIds = webuserCalendarIds, remoteFolderIds = remoteFolderIds, webuserIds = webuserIds)

        val localVarResponse = request<Map<String, Any?>, RemoteaccountAccountSyncResponse>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemoteaccountAccountSyncResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation synchronizeTasks
    *
    * @param dateTimeStart  (optional)
    * @param dateTimeEnd  (optional)
    * @param webuserCalendarIds  (optional)
    * @param remoteFolderIds  (optional)
    * @param webuserIds  (optional)
    * @return RequestConfig
    */
    fun synchronizeTasksRequestConfig(dateTimeStart: kotlin.String?, dateTimeEnd: kotlin.String?, webuserCalendarIds: kotlin.collections.List<kotlin.Int>?, remoteFolderIds: kotlin.collections.List<kotlin.Int>?, webuserIds: kotlin.collections.List<kotlin.Int>?) : RequestConfig<Map<String, Any?>> {
        val localVariableBody = mapOf("dateTimeStart" to dateTimeStart, "dateTimeEnd" to dateTimeEnd, "webuserCalendarIds" to webuserCalendarIds, "remoteFolderIds" to remoteFolderIds, "webuserIds" to webuserIds)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "application/x-www-form-urlencoded")

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/crm/api/agenda/account/tasksSync",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
