/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param gatewayId 
 * @param name 
 * @param defaultLang 
 */

data class AdminCredentialResponse (
    @Json(name = "gatewayId")
    val gatewayId: kotlin.Int,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "defaultLang")
    val defaultLang: kotlin.String
)

