/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.AccessRights

import com.squareup.moshi.Json

/**
 * 
 *
 * @param calendarId Unique identifier of the calendar.
 * @param ownerId Unique identifier of the owner user of the calendar.
 * @param label Summary label of the calendar.
 * @param isCompleted Is this the calendar for completed events.
 * @param accessRights 
 * @param color hex color of the calendar.
 * @param textColor hex text color of the calendar.
 */

data class CalendarsCalendar (

    /* Unique identifier of the calendar. */
    @Json(name = "calendarId")
    val calendarId: kotlin.Int,

    /* Unique identifier of the owner user of the calendar. */
    @Json(name = "ownerId")
    val ownerId: kotlin.Int,

    /* Summary label of the calendar. */
    @Json(name = "label")
    val label: kotlin.String,

    /* Is this the calendar for completed events. */
    @Json(name = "isCompleted")
    val isCompleted: kotlin.Boolean,

    @Json(name = "accessRights")
    val accessRights: AccessRights,

    /* hex color of the calendar. */
    @Json(name = "color")
    val color: kotlin.String? = null,

    /* hex text color of the calendar. */
    @Json(name = "textColor")
    val textColor: kotlin.String? = null

)

