/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid environment name
 * @param displayName environment name
 * @param email environment name
 */

data class Contextuser (

    /* environment name */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* environment name */
    @Json(name = "displayName")
    val displayName: kotlin.String,

    /* environment name */
    @Json(name = "email")
    val email: kotlin.String

)

