/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.FieldValue
import com.equisoft.connect.sdk.models.Translation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique numerical identifier of the field value.
 * @param label Value label in the current language.
 * @param translations Value labels in available languages.
 * @param systemName 
 */

data class ContactContactAdditionalInformationLanguage (

    /* Unique numerical identifier of the field value. */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Value label in the current language. */
    @Json(name = "label")
    val label: kotlin.String,

    /* Value labels in available languages. */
    @Json(name = "translations")
    val translations: kotlin.collections.List<Translation>? = null,

    @Json(name = "systemName")
    val systemName: kotlin.String? = null

)

