/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param repCode 
 * @param status 
 * @param isActive 
 * @param webUserName 
 * @param webUserEmail 
 * @param dealerCode 
 * @param district 
 * @param us 
 * @param creationDate 
 * @param approvalDate 
 * @param refusalDate 
 * @param revocationDate 
 */

data class CredentialDto (
    @Json(name = "id")
    val id: kotlin.Int,
    @Json(name = "repCode")
    val repCode: kotlin.String?,
    @Json(name = "status")
    val status: kotlin.String,
    @Json(name = "isActive")
    val isActive: kotlin.Boolean,
    @Json(name = "webUserName")
    val webUserName: kotlin.String,
    @Json(name = "webUserEmail")
    val webUserEmail: kotlin.String,
    @Json(name = "dealerCode")
    val dealerCode: kotlin.String? = null,
    @Json(name = "district")
    val district: kotlin.String? = null,
    @Json(name = "us")
    val us: kotlin.String? = null,
    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,
    @Json(name = "approvalDate")
    val approvalDate: kotlin.String? = null,
    @Json(name = "refusalDate")
    val refusalDate: kotlin.String? = null,
    @Json(name = "revocationDate")
    val revocationDate: kotlin.String? = null
)

