/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param id Id
 * @param uuid Uuid
 * @param databaseName Database name
 * @param displayName Display name
 * @param organizationUuid Organization uuid
 * @param profile Profile
 * @param state Database state
 */

data class DatabasesDatabase (
    /* Id */
    @Json(name = "id")
    val id: kotlin.Int,
    /* Uuid */
    @Json(name = "uuid")
    val uuid: kotlin.String,
    /* Database name */
    @Json(name = "databaseName")
    val databaseName: kotlin.String,
    /* Display name */
    @Json(name = "displayName")
    val displayName: kotlin.String,
    /* Organization uuid */
    @Json(name = "organizationUuid")
    val organizationUuid: kotlin.String,
    /* Profile */
    @Json(name = "profile")
    val profile: kotlin.String? = null,
    /* Database state */
    @Json(name = "state")
    val state: kotlin.String? = null
)

