/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param date 
 * @param dateTime 
 */

data class DateOrDateTime (
    @Json(name = "date")
    val date: kotlin.String? = null,
    @Json(name = "dateTime")
    val dateTime: java.time.OffsetDateTime? = null
)

