/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Id
 * @param nameFr French name
 * @param nameEn English name
 * @param network SFL|DFSI|DFSIN|VMD
 * @param databaseCount Code
 * @param code Code
 * @param organizationUuid Organization Unique Id
 */

data class DsfFinancialCenter (

    /* Id */
    @Json(name = "id")
    val id: kotlin.Int,

    /* French name */
    @Json(name = "nameFr")
    val nameFr: kotlin.String,

    /* English name */
    @Json(name = "nameEn")
    val nameEn: kotlin.String,

    /* SFL|DFSI|DFSIN|VMD */
    @Json(name = "network")
    val network: kotlin.String,

    /* Code */
    @Json(name = "databaseCount")
    val databaseCount: kotlin.Int,

    /* Code */
    @Json(name = "code")
    val code: kotlin.String? = null,

    /* Organization Unique Id */
    @Json(name = "organizationUuid")
    val organizationUuid: kotlin.String? = null

)

