/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param username | null
 * @param password | null
 * @param repcode 
 * @param isADealerCode 
 */

data class GatewaysCredentials (

    /* | null */
    @Json(name = "username")
    val username: kotlin.String,

    /* | null */
    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "repcode")
    val repcode: kotlin.String? = null,

    @Json(name = "isADealerCode")
    val isADealerCode: kotlin.Boolean? = null

)

