/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ssnList The list will contain formatted SSNs, i.e. \"123 456 789\"
 */

data class GatewaysCredentialsWithSsnAllOf (

    /* The list will contain formatted SSNs, i.e. \"123 456 789\" */
    @Json(name = "ssnList")
    val ssnList: kotlin.collections.List<kotlin.String>? = null

)

