/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param username 
 * @param refreshToken 
 */

data class Handlersoauth2assetbookAssetBookTokenPostBody (
    @Json(name = "Username")
    val username: kotlin.String,
    @Json(name = "RefreshToken")
    val refreshToken: kotlin.String
)

