/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.InternalNotesNoteAccessRights
import com.equisoft.connect.sdk.models.InternalNotesNoteAuthor
import com.equisoft.connect.sdk.models.InternalNotesNoteCurrentRevision
import com.equisoft.connect.sdk.models.InternalNotesNoteRevision

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique numerical identifier.
 * @param author 
 * @param firstRevisionCreatedAt 
 * @param accessRights 
 * @param currentRevision 
 * @param previousRevisions 
 */

data class InternalNotesNote (

    /* Unique numerical identifier. */
    @Json(name = "id")
    val id: kotlin.Int?,

    @Json(name = "author")
    val author: InternalNotesNoteAuthor?,

    @Json(name = "firstRevisionCreatedAt")
    val firstRevisionCreatedAt: java.time.OffsetDateTime?,

    @Json(name = "accessRights")
    val accessRights: InternalNotesNoteAccessRights?,

    @Json(name = "currentRevision")
    val currentRevision: InternalNotesNoteCurrentRevision?,

    @Json(name = "previousRevisions")
    val previousRevisions: kotlin.collections.List<InternalNotesNoteRevision>? = null

)

