/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param uuid Globally unique identifier.
 * @param displayName Author name
 * @param id Unique numerical identifier.
 */

data class InternalNotesAuthor (
    /* Globally unique identifier. */
    @Json(name = "uuid")
    val uuid: kotlin.String?,
    /* Author name */
    @Json(name = "displayName")
    val displayName: kotlin.String?,
    /* Unique numerical identifier. */
    @Json(name = "id")
    val id: kotlin.Int? = null
)

