/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.InternalNotesAuthor

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid Globally unique identifier.
 * @param displayName Author name
 * @param id Unique numerical identifier.
 */

data class InternalNotesNoteAuthor (

    /* Globally unique identifier. */
    @Json(name = "uuid")
    val uuid: kotlin.String?,

    /* Author name */
    @Json(name = "displayName")
    val displayName: kotlin.String?,

    /* Unique numerical identifier. */
    @Json(name = "id")
    val id: kotlin.Int? = null

)

