/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param insuranceClass 
 * @param smoker 
 */

data class LegacyfinancePolicyCoverageInsured (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "insuranceClass")
    val insuranceClass: kotlin.String? = null,

    @Json(name = "smoker")
    val smoker: kotlin.String? = null

)

