/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param category 
 * @param marketValue 
 * @param marketValueDate 
 * @param showWarning 
 * @param foreignCurrency 
 */

data class LegacyfinancePlanSummary (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "marketValue")
    val marketValue: kotlin.String? = null,

    @Json(name = "marketValueDate")
    val marketValueDate: kotlin.String? = null,

    @Json(name = "showWarning")
    val showWarning: kotlin.String? = null,

    @Json(name = "foreignCurrency")
    val foreignCurrency: kotlin.String? = null

)

