/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique id
 * @param uuid Contact UUID
 * @param typeContact type of the contact
 * @param indOrg type INDIVIDUAL OR ORGANIZATION
 * @param displayName display name of the contact
 * @param firstName first name of the contact
 * @param nickname nickname of the contact
 * @param middleName middle name of the contact
 * @param lastName last name of the contact
 * @param corporationName first line of corporation name (Organization)
 * @param corporationNameLine2 second line of corporation name (Organization)
 * @param rank rank of the contact. (Industrial Alliance only)
 */

data class LegacycontactContact (

    /* Unique id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Contact UUID */
    @Json(name = "uuid")
    val uuid: kotlin.String? = null,

    /* type of the contact */
    @Json(name = "typeContact")
    val typeContact: kotlin.String? = null,

    /* type INDIVIDUAL OR ORGANIZATION */
    @Json(name = "indOrg")
    val indOrg: kotlin.String? = null,

    /* display name of the contact */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    /* first name of the contact */
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    /* nickname of the contact */
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    /* middle name of the contact */
    @Json(name = "middleName")
    val middleName: kotlin.String? = null,

    /* last name of the contact */
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,

    /* first line of corporation name (Organization) */
    @Json(name = "corporationName")
    val corporationName: kotlin.String? = null,

    /* second line of corporation name (Organization) */
    @Json(name = "corporationNameLine2")
    val corporationNameLine2: kotlin.String? = null,

    /* rank of the contact. (Industrial Alliance only) */
    @Json(name = "rank")
    val rank: kotlin.String? = null

)

