/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param externalKey The file external key
 * @param base64EncodedData file data encoded in base 64
 */

data class LegacyDocumentBase64FilePayloadItemAllOf (

    /* The file external key */
    @Json(name = "externalKey")
    val externalKey: kotlin.String? = null,

    /* file data encoded in base 64 */
    @Json(name = "base64EncodedData")
    val base64EncodedData: kotlin.String? = null

)

