/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.LegacyfinancePolicyCoverage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param policyNb 
 * @param lineOfBusiness 
 * @param lineOfBusinessLabel 
 * @param type 
 * @param owner 
 * @param carrier 
 * @param issueDate 
 * @param endDate 
 * @param annualPremium 
 * @param modalPremium 
 * @param annualizedPremium 
 * @param premiumMode 
 * @param isOwner 
 * @param isInsured 
 * @param isBeneficiary 
 * @param coverages 
 * @param status Policy status
 */

data class LegacyfinancePolicy (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "policyNb")
    val policyNb: kotlin.String? = null,

    @Json(name = "lineOfBusiness")
    val lineOfBusiness: kotlin.String? = null,

    @Json(name = "lineOfBusinessLabel")
    val lineOfBusinessLabel: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "carrier")
    val carrier: kotlin.String? = null,

    @Json(name = "issueDate")
    val issueDate: kotlin.String? = null,

    @Json(name = "endDate")
    val endDate: kotlin.String? = null,

    @Json(name = "annualPremium")
    val annualPremium: kotlin.String? = null,

    @Json(name = "modalPremium")
    val modalPremium: kotlin.String? = null,

    @Json(name = "annualizedPremium")
    val annualizedPremium: kotlin.String? = null,

    @Json(name = "premiumMode")
    val premiumMode: kotlin.String? = null,

    @Json(name = "isOwner")
    val isOwner: kotlin.String? = null,

    @Json(name = "isInsured")
    val isInsured: kotlin.String? = null,

    @Json(name = "isBeneficiary")
    val isBeneficiary: kotlin.String? = null,

    @Json(name = "coverages")
    val coverages: kotlin.collections.List<LegacyfinancePolicyCoverage>? = null,

    /* Policy status */
    @Json(name = "status")
    val status: kotlin.String? = null

)

