/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param contactId Fetch only document that are related to this contact id.
 * @param limit Limit the result to $limit
 * @param systemType Filter by system type.
 */

data class LegacydocumentGetListOptions (
    /* Fetch only document that are related to this contact id. */
    @Json(name = "contact_id")
    val contactId: kotlin.Int? = null,
    /* Limit the result to $limit */
    @Json(name = "limit")
    val limit: kotlin.Int? = null,
    /* Filter by system type. */
    @Json(name = "system_type")
    val systemType: kotlin.String? = null
)

