/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param capsilFile 
 * @param univerisFile 
 * @param dataphileFile 
 * @param type 
 */

data class MovementClientBaseUsingFileMovementPayloadAllOf (

    @Json(name = "sourceDatabase")
    val sourceDatabase: kotlin.String? = null,

    @Json(name = "sourceUser")
    val sourceUser: kotlin.String? = null,

    @Json(name = "destinationDatabase")
    val destinationDatabase: kotlin.String? = null,

    @Json(name = "destinationUser")
    val destinationUser: kotlin.String? = null,

    @Json(name = "capsilFile")
    val capsilFile: kotlin.String? = null,

    @Json(name = "univerisFile")
    val univerisFile: kotlin.String? = null,

    @Json(name = "dataphileFile")
    val dataphileFile: kotlin.String? = null,

    @Json(name = "type")
    val type: MovementClientBaseUsingFileMovementPayloadAllOf.Type? = null

) {

    /**
     * 
     *
     * Values: CLIENTBASE_USING_FILE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_FILE") CLIENTBASE_USING_FILE("CLIENTBASE_USING_FILE");
    }
}

