/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementDatabase
import com.equisoft.connect.sdk.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 *
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param capsil 
 * @param univeris 
 * @param dataphile 
 * @param type 
 */

data class MovementClientBaseUsingFileMovementAllOf (

    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase? = null,

    @Json(name = "sourceUser")
    val sourceUser: MovementUser? = null,

    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase? = null,

    @Json(name = "destinationUser")
    val destinationUser: MovementUser? = null,

    @Json(name = "capsil")
    val capsil: kotlin.Boolean? = null,

    @Json(name = "univeris")
    val univeris: kotlin.Boolean? = null,

    @Json(name = "dataphile")
    val dataphile: kotlin.Boolean? = null,

    @Json(name = "type")
    val type: MovementClientBaseUsingFileMovementAllOf.Type? = Type.CLIENTBASE_USING_FILE

) {

    /**
     * 
     *
     * Values: CLIENTBASE_USING_FILE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_FILE") CLIENTBASE_USING_FILE("CLIENTBASE_USING_FILE");
    }
}

