/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementDatabase
import com.equisoft.connect.sdk.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param capsil 
 * @param univeris 
 * @param dataphile 
 */

data class MovementClientBaseUsingFileMovementAllOf (
    @Json(name = "type")
    val type: MovementClientBaseUsingFileMovementAllOf.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "sourceUser")
    val sourceUser: MovementUser,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "destinationUser")
    val destinationUser: MovementUser,
    @Json(name = "capsil")
    val capsil: kotlin.Boolean? = null,
    @Json(name = "univeris")
    val univeris: kotlin.Boolean? = null,
    @Json(name = "dataphile")
    val dataphile: kotlin.Boolean? = null
) {

    /**
     * 
     * Values: CLIENTBASE_USING_FILE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_FILE") CLIENTBASE_USING_FILE("CLIENTBASE_USING_FILE");
    }
}

