/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param status 
 * @param availableAction 
 * @param scheduledDate 
 * @param processedDate 
 * @param addedDate 
 * @param addedBy 
 * @param cancelledDate 
 * @param cancelledBy 
 */

interface MovementMovement {

    @Json(name = "id")
    val id: kotlin.Int?
    @Json(name = "status")
    val status: kotlin.String?
    @Json(name = "availableAction")
    val availableAction: kotlin.String?
    @Json(name = "scheduledDate")
    val scheduledDate: kotlin.String?
    @Json(name = "processedDate")
    val processedDate: kotlin.String?
    @Json(name = "addedDate")
    val addedDate: kotlin.String?
    @Json(name = "addedBy")
    val addedBy: MovementUser?
    @Json(name = "cancelledDate")
    val cancelledDate: kotlin.String?
    @Json(name = "cancelledBy")
    val cancelledBy: MovementUser?
}

