/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param capsilFile 
 * @param univerisFile 
 * @param dataphileFile 
 */

data class MovementClientBaseUsingFileMovementPayloadAllOf (
    @Json(name = "type")
    val type: MovementClientBaseUsingFileMovementPayloadAllOf.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: kotlin.String,
    @Json(name = "sourceUser")
    val sourceUser: kotlin.String,
    @Json(name = "destinationDatabase")
    val destinationDatabase: kotlin.String,
    @Json(name = "destinationUser")
    val destinationUser: kotlin.String,
    @Json(name = "capsilFile")
    val capsilFile: kotlin.String? = null,
    @Json(name = "univerisFile")
    val univerisFile: kotlin.String? = null,
    @Json(name = "dataphileFile")
    val dataphileFile: kotlin.String? = null
) {

    /**
     * 
     * Values: CLIENTBASE_USING_FILE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_FILE") CLIENTBASE_USING_FILE("CLIENTBASE_USING_FILE");
    }
}

