/**
 * Equisoft /connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementClientBaseUsingDistributionListMovementPayloadAllOf
import com.equisoft.connect.sdk.models.MovementMovementPayload

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param transferOption 
 * @param date 
 * @param now 
 * @param sourceDistributionList 
 * @param datagatewayAccessMappings 
 */

data class MovementClientBaseUsingDistributionListMovementPayload (

    @Json(name = "type")
    val type: MovementClientBaseUsingDistributionListMovementPayload.Type = Type.CLIENTBASE_USING_DISTLIST,

    @Json(name = "sourceDatabase")
    val sourceDatabase: kotlin.String,

    @Json(name = "sourceUser")
    val sourceUser: kotlin.String,

    @Json(name = "destinationDatabase")
    val destinationDatabase: kotlin.String,

    @Json(name = "destinationUser")
    val destinationUser: kotlin.String,

    @Json(name = "transferOption")
    val transferOption: kotlin.String,

    @Json(name = "date")
    override val date: kotlin.String? = null,

    @Json(name = "now")
    override val now: kotlin.Boolean? = null,

    @Json(name = "sourceDistributionList")
    val sourceDistributionList: kotlin.String? = null,

    @Json(name = "datagatewayAccessMappings")
    val datagatewayAccessMappings: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) : MovementMovementPayload {

    /**
     * 
     *
     * Values: CLIENTBASE_USING_DISTLIST
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_DISTLIST") CLIENTBASE_USING_DISTLIST("CLIENTBASE_USING_DISTLIST");
    }
}

