/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementDatabase
import com.equisoft.connect.sdk.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param destinationDatabase 
 * @param users 
 */

data class MovementMoveMovementAllOf (
    @Json(name = "type")
    val type: MovementMoveMovementAllOf.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "users")
    val users: kotlin.collections.List<MovementUser>
) {

    /**
     * 
     * Values: MOVE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "MOVE") MOVE("MOVE");
    }
}

