/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.MovementClientBaseUsingFileMovementAllOf
import com.equisoft.connect.sdk.models.MovementDatabase
import com.equisoft.connect.sdk.models.MovementMovement
import com.equisoft.connect.sdk.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param id 
 * @param status 
 * @param availableAction 
 * @param scheduledDate 
 * @param processedDate 
 * @param addedDate 
 * @param addedBy 
 * @param cancelledDate 
 * @param cancelledBy 
 * @param capsil 
 * @param univeris 
 * @param dataphile 
 */

data class MovementClientBaseUsingFileMovement (
    @Json(name = "type")
    val type: MovementClientBaseUsingFileMovement.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "sourceUser")
    val sourceUser: MovementUser,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "destinationUser")
    val destinationUser: MovementUser,
    @Json(name = "id")
    override val id: kotlin.Int? = null,
    @Json(name = "status")
    override val status: kotlin.String? = null,
    @Json(name = "availableAction")
    override val availableAction: kotlin.String? = null,
    @Json(name = "scheduledDate")
    override val scheduledDate: kotlin.String? = null,
    @Json(name = "processedDate")
    override val processedDate: kotlin.String? = null,
    @Json(name = "addedDate")
    override val addedDate: kotlin.String? = null,
    @Json(name = "addedBy")
    override val addedBy: MovementUser? = null,
    @Json(name = "cancelledDate")
    override val cancelledDate: kotlin.String? = null,
    @Json(name = "cancelledBy")
    override val cancelledBy: MovementUser? = null,
    @Json(name = "capsil")
    val capsil: kotlin.Boolean? = null,
    @Json(name = "univeris")
    val univeris: kotlin.Boolean? = null,
    @Json(name = "dataphile")
    val dataphile: kotlin.Boolean? = null
) : MovementMovement {

    /**
     * 
     * Values: CLIENTBASE_USING_FILE
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_FILE") CLIENTBASE_USING_FILE("CLIENTBASE_USING_FILE");
    }
}

