/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.connect.sdk.models

import com.equisoft.connect.sdk.models.Mxrecipient

import com.squareup.moshi.Json

/**
 * 
 * @param invalidRecipients invalidRecipients
 */

data class MxvalidateRecipientsResponse (
    /* invalidRecipients */
    @Json(name = "invalidRecipients")
    val invalidRecipients: kotlin.collections.List<Mxrecipient>
)

