/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models


import com.squareup.moshi.Json

/**
 * 
 * @param tz $tz
 * @param locale $locale
 * @param timeFormat $timeFormat
 * @param firstDayOfWeek $firstDayOfWeek
 */

data class Contextpreferences (
    /* $tz */
    @Json(name = "tz")
    val tz: kotlin.String,
    /* $locale */
    @Json(name = "locale")
    val locale: kotlin.String,
    /* $timeFormat */
    @Json(name = "timeFormat")
    val timeFormat: kotlin.String,
    /* $firstDayOfWeek */
    @Json(name = "firstDayOfWeek")
    val firstDayOfWeek: kotlin.String
)

