/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models


import com.squareup.moshi.Json

/**
 * 
 * @param clientKey 
 * @param version 
 */

data class GatewaysAccessesEquisoftAnalyzeAccessAllOf (
    @Json(name = "clientKey")
    val clientKey: kotlin.String,
    @Json(name = "version")
    val version: GatewaysAccessesEquisoftAnalyzeAccessAllOf.Version
) {

    /**
     * 
     * Values: nATIVE,lEGACY
     */
    enum class Version(val value: kotlin.String) {
        @Json(name = "NATIVE") nATIVE("NATIVE"),
        @Json(name = "LEGACY") lEGACY("LEGACY");
    }
}

