/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.GatewaysAccessesEquisoftAnalyzeAccessAllOf
import equisoft/openapi.models.GatewaysaccessesAccess
import equisoft/openapi.models.GatewaysaccessesUser

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param users 
 * @param clientKey 
 * @param version 
 * @param type 
 */

data class GatewaysaccessesEquisoftAnalyzeAccess (
    @Json(name = "id")
    override val id: kotlin.Int,
    @Json(name = "users")
    override val users: kotlin.collections.List<GatewaysaccessesUser>,
    @Json(name = "clientKey")
    val clientKey: kotlin.String,
    @Json(name = "version")
    val version: GatewaysaccessesEquisoftAnalyzeAccess.Version,
    @Json(name = "type")
    override val type: GatewaysaccessesEquisoftAnalyzeAccess.Type? = null
) : GatewaysaccessesAccess {

    /**
     * 
     * Values: nATIVE,lEGACY
     */
    enum class Version(val value: kotlin.String) {
        @Json(name = "NATIVE") nATIVE("NATIVE"),
        @Json(name = "LEGACY") lEGACY("LEGACY");
    }
}

