/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.InternalNotesNoteRevision
import equisoft/openapi.models.OneOfLessThanAccessRightsGreaterThan
import equisoft/openapi.models.OneOfLessThanInternalNotesAuthorGreaterThan
import equisoft/openapi.models.OneOfLessThanInternalNotesNoteRevisionGreaterThan

import com.squareup.moshi.Json

/**
 * 
 * @param id Unique numerical identifier.
 * @param author 
 * @param firstRevisionCreatedAt 
 * @param accessRights 
 * @param currentRevision 
 * @param previousRevisions 
 */

data class InternalNotesNote (
    /* Unique numerical identifier. */
    @Json(name = "id")
    val id: kotlin.Int?,
    @Json(name = "author")
    val author: OneOfLessThanInternalNotesAuthorGreaterThan?,
    @Json(name = "firstRevisionCreatedAt")
    val firstRevisionCreatedAt: java.time.OffsetDateTime?,
    @Json(name = "accessRights")
    val accessRights: OneOfLessThanAccessRightsGreaterThan?,
    @Json(name = "currentRevision")
    val currentRevision: OneOfLessThanInternalNotesNoteRevisionGreaterThan?,
    @Json(name = "previousRevisions")
    val previousRevisions: kotlin.collections.List<InternalNotesNoteRevision>? = null
)

