/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models


import com.squareup.moshi.Json

/**
 * 
 * @param groupId User unique identifier
 * @param name Group name
 */

data class LegacyprovisioningGroupItem (
    /* User unique identifier */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,
    /* Group name */
    @Json(name = "name")
    val name: kotlin.String? = null
)

