/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models


import com.squareup.moshi.Json

/**
 * 
 * @param id id of the user
 * @param displayName display name of the user
 * @param email email of the user
 */

data class LegacyUser (
    /* id of the user */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* display name of the user */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    /* email of the user */
    @Json(name = "email")
    val email: kotlin.String? = null
)

