/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.LegacydocumentDocumentPayload

import com.squareup.moshi.Json

/**
 * Wrapper for Legacy payload argument
 * @param payload 
 */

data class LegacydocumentDocumentPayloadRequest (
    @Json(name = "payload")
    val payload: LegacydocumentDocumentPayload
)

