/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.MovementDatabase
import equisoft/openapi.models.MovementDistributionList
import equisoft/openapi.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param transferOption 
 * @param sourceDistributionList 
 * @param datagatewayAccessMappings 
 */

data class MovementClientBaseUsingDistributionListMovementAllOf (
    @Json(name = "type")
    val type: MovementClientBaseUsingDistributionListMovementAllOf.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "sourceUser")
    val sourceUser: MovementUser,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "destinationUser")
    val destinationUser: MovementUser,
    @Json(name = "transferOption")
    val transferOption: kotlin.String,
    @Json(name = "sourceDistributionList")
    val sourceDistributionList: MovementDistributionList? = null,
    @Json(name = "datagatewayAccessMappings")
    val datagatewayAccessMappings: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) {

    /**
     * 
     * Values: cLIENTBASEUSINGDISTLIST
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_DISTLIST") cLIENTBASEUSINGDISTLIST("CLIENTBASE_USING_DISTLIST");
    }
}

