/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.MovementUserTuplePayload

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param destinationDatabase 
 * @param userTuples 
 */

data class MovementCopyMovementPayloadAllOf (
    @Json(name = "type")
    val type: MovementCopyMovementPayloadAllOf.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: kotlin.String,
    @Json(name = "destinationDatabase")
    val destinationDatabase: kotlin.String,
    @Json(name = "userTuples")
    val userTuples: kotlin.collections.List<MovementUserTuplePayload>? = null
) {

    /**
     * 
     * Values: cOPY
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "COPY") cOPY("COPY");
    }
}

