/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.MovementCopyMovementAllOf
import equisoft/openapi.models.MovementDatabase
import equisoft/openapi.models.MovementMovement
import equisoft/openapi.models.MovementUser
import equisoft/openapi.models.MovementUserTuple

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param destinationDatabase 
 * @param userTuples 
 * @param id 
 * @param status 
 * @param availableAction 
 * @param scheduledDate 
 * @param processedDate 
 * @param addedDate 
 * @param addedBy 
 * @param cancelledDate 
 * @param cancelledBy 
 */

data class MovementCopyMovement (
    @Json(name = "type")
    val type: MovementCopyMovement.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "userTuples")
    val userTuples: kotlin.collections.List<MovementUserTuple>,
    @Json(name = "id")
    override val id: kotlin.Int? = null,
    @Json(name = "status")
    override val status: kotlin.String? = null,
    @Json(name = "availableAction")
    override val availableAction: kotlin.String? = null,
    @Json(name = "scheduledDate")
    override val scheduledDate: kotlin.String? = null,
    @Json(name = "processedDate")
    override val processedDate: kotlin.String? = null,
    @Json(name = "addedDate")
    override val addedDate: kotlin.String? = null,
    @Json(name = "addedBy")
    override val addedBy: MovementUser? = null,
    @Json(name = "cancelledDate")
    override val cancelledDate: kotlin.String? = null,
    @Json(name = "cancelledBy")
    override val cancelledBy: MovementUser? = null
) : MovementMovement {

    /**
     * 
     * Values: cOPY
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "COPY") cOPY("COPY");
    }
}

