/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.MovementClientBaseUsingDistributionListMovementAllOf
import equisoft/openapi.models.MovementDatabase
import equisoft/openapi.models.MovementDistributionList
import equisoft/openapi.models.MovementMovement
import equisoft/openapi.models.MovementUser

import com.squareup.moshi.Json

/**
 * 
 * @param type 
 * @param sourceDatabase 
 * @param sourceUser 
 * @param destinationDatabase 
 * @param destinationUser 
 * @param transferOption 
 * @param id 
 * @param status 
 * @param availableAction 
 * @param scheduledDate 
 * @param processedDate 
 * @param addedDate 
 * @param addedBy 
 * @param cancelledDate 
 * @param cancelledBy 
 * @param sourceDistributionList 
 * @param datagatewayAccessMappings 
 */

data class MovementClientBaseUsingDistributionListMovement (
    @Json(name = "type")
    val type: MovementClientBaseUsingDistributionListMovement.Type,
    @Json(name = "sourceDatabase")
    val sourceDatabase: MovementDatabase,
    @Json(name = "sourceUser")
    val sourceUser: MovementUser,
    @Json(name = "destinationDatabase")
    val destinationDatabase: MovementDatabase,
    @Json(name = "destinationUser")
    val destinationUser: MovementUser,
    @Json(name = "transferOption")
    val transferOption: kotlin.String,
    @Json(name = "id")
    override val id: kotlin.Int? = null,
    @Json(name = "status")
    override val status: kotlin.String? = null,
    @Json(name = "availableAction")
    override val availableAction: kotlin.String? = null,
    @Json(name = "scheduledDate")
    override val scheduledDate: kotlin.String? = null,
    @Json(name = "processedDate")
    override val processedDate: kotlin.String? = null,
    @Json(name = "addedDate")
    override val addedDate: kotlin.String? = null,
    @Json(name = "addedBy")
    override val addedBy: MovementUser? = null,
    @Json(name = "cancelledDate")
    override val cancelledDate: kotlin.String? = null,
    @Json(name = "cancelledBy")
    override val cancelledBy: MovementUser? = null,
    @Json(name = "sourceDistributionList")
    val sourceDistributionList: MovementDistributionList? = null,
    @Json(name = "datagatewayAccessMappings")
    val datagatewayAccessMappings: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
) : MovementMovement {

    /**
     * 
     * Values: cLIENTBASEUSINGDISTLIST
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "CLIENTBASE_USING_DISTLIST") cLIENTBASEUSINGDISTLIST("CLIENTBASE_USING_DISTLIST");
    }
}

