/**
* Equisoft /connect API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package equisoft/openapi.models

import equisoft/openapi.models.AnyType

import com.squareup.moshi.Json

/**
 * 
 * @param to to recipients
 * @param cc cc recipients
 * @param bcc bcc recipients
 * @param groups group recipients
 * @param contacts contact recipients
 */

data class MxrecipientsPayload (
    /* to recipients */
    @Json(name = "to")
    val to: kotlin.String,
    /* cc recipients */
    @Json(name = "cc")
    val cc: kotlin.String,
    /* bcc recipients */
    @Json(name = "bcc")
    val bcc: kotlin.String,
    /* group recipients */
    @Json(name = "groups")
    val groups: AnyType?,
    /* contact recipients */
    @Json(name = "contacts")
    val contacts: AnyType?
)

